// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package apitest

import (
	"github.com/Sovianum/figma-search-app/src/api"
	"github.com/Sovianum/figma-search-app/src/api/apiwire"
	"github.com/Sovianum/figma-search-app/src/apitest/dbmockmod"
	"github.com/Sovianum/figma-search-app/src/client/clienttag"
	"github.com/Sovianum/figma-search-app/src/domain/tag/tagimpl"
	"github.com/google/wire"
	"github.com/gusaul/go-dynamock"
)

// Injectors from api_init.go:

func InitializeAPI() *api.API {
	dbWithMock := dbmockmod.NewDBWithMock()
	dynamoDBAPI := dbmockmod.NewDB(dbWithMock)
	dao := tagimpl.NewDAO(dynamoDBAPI)
	manager := tagimpl.NewManager(dao)
	converter := clienttag.NewConverter()
	tagger := tagimpl.NewTagger()
	tagEndpoints := api.NewTagEndpoints(manager, converter, tagger)
	apiAPI := api.NewAPI(tagEndpoints)
	return apiAPI
}

func InitializeMock() *dynamock.DynaMock {
	dbWithMock := dbmockmod.NewDBWithMock()
	dynaMock := dbmockmod.NewMock(dbWithMock)
	return dynaMock
}

// api_init.go:

var M = wire.NewSet(apiwire.M, dbmockmod.M)
